### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by tfcarlin** [Tonio101/YoLinkAPI_V2#3]
Hi,

I obviously don't expect you to provide tech support for my environment so let me know if these are just annoying. I recently received the following. I have a motion sensor though removed it from the .json configuration file as it doesn't have a model. 

Thanks,

Tim

2022-04-07 06:29:27:yolink_devices:INFO - Id: xxx
Name: Back Yd Hose in Famy Rm Leak
Type: Leak Sensor
Event: LeakSensor.Report
Token: xxx
Event Time: 2022-04-07 06:29:26
Current Time: 2022-04-07 06:29:27
Current State: -1
: -1
2022-04-07 06:29:27:yolink_consumer:DEBUG - Successfully processed entry, number of entries in the queue: 0
2022-04-07 06:54:43:yolink_consumer:DEBUG - Pulled from the output_q
2022-04-07 06:54:43:yolink_consumer:DEBUG - {'event': 'LeakSensor.Alert', 'time': 1649336082875, 'msgid': '1649336082874', 'data': {'sensorMode': 'WaterLeak', 'state': 'alert', 'battery': 4, 'version': '030d', 'devTemperature': 27, 'loraInfo': {'signal': -61, 'gatewayId': 'xxx', 'gateways': 1}, 'stateChangedAt': 1649336082873}, 'deviceId': 'xxx'}
Exception in thread consumer:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File ".../YoLinkAPI_V2/src/models/yolink_consumer.py", line 32, in run
    rc = self.process_entry(payload)
  File "/...//YoLinkAPI_V2/src/models/yolink_consumer.py", line 64, in process_entry
    log.debug("\n{0}\n".format(device))
  File "/...//YoLinkAPI_V2/src/models/yolink_devices.py", line 226, in __str__
    str(self.get_state())
  File "/...//YoLinkAPI_V2/src/models/yolink_devices.py", line 221, in get_state
    return EVENT_STATE[self.get_device_data()['state']]
KeyError: 'alert'

**Comment by Tonio101** [comment]
@tfcarlin No problem at all, please do reach out if you run into additional problems. Committed the fix, pull the latest changes from master. It seems like I never ran into an `alert` state for my Leak sensors.
